#!/usr/bin/env bash
DIRETORIO_PRODUCAO='/home/potencial/www'

#!/bin/sh
AUTHORINFO=$(git var GIT_AUTHOR_IDENT) || exit 1
NAME=$(printf '%s\n' "${AUTHORINFO}" | sed -n 's/^\(.*\) <.*$/\1/p')
EMAIL=$(printf '%s\n' "${AUTHORINFO}" | sed -n 's/^.* <\(.*\)> .*$/\1/p')
[ "${NAME}" != root ] && [ "${EMAIL}" != "root@localhost" ] || {
    cat <<EOF >&2
Please commit under your own name and email instead of "${NAME} <${EMAIL}>":
GIT_AUTHOR_NAME="Your Name" GIT_AUTHOR_EMAIL="your@email.com" git commit
EOF
	exit 1
}
echo "***************************************"
echo "*                                    **"
echo "*            Deploy Git              **"
echo "*                                    **"
echo "***************************************"
echo "***************************************"
echo "*            Deploy Git              **"
echo "***************************************"
echo "***************************************"
echo "***************************************"
echo "**                                   **"
echo "**    Olá $NAME                      **"
echo "**                                   **"
echo "***************************************"

#SUBJECT="Deploy successful"
#BODY="You've successfully deployed the branch:"

while read oldrev newrev ref
do
	branch=`echo $ref | cut -d/ -f3`

	if [ "$branch" ] ; then
		cd $DIRETORIO_PRODUCAO
		env -i git pull origin $branch
		echo "***************************************"
		echo "**                                   **"
		echo "**                                   **"
		echo "**    Branch $branch atualizado!   **"
		echo "**                                   **"
		echo "**                                   **"
		echo "***************************************"
	fi
done
